# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
       - targets: ["localhost:9093"] 

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "postgresql_db20"
    static_configs:
      - targets: ["10.129.0.21:9187"]
        #alias: "postgres"
  - job_name: "PostgresDB"
    static_configs:
      - targets: ['10.129.0.24:9187','10.129.0.10:9187']
        #  - job_name: "postgres-node1"
        #    static_configs:
        #      - targets: ["10.129.0.10:9187"]
  - job_name: "PatroniCl"
    static_configs:
      - targets: ['10.129.0.24:9933','10.129.0.10:9933']
        #  - job_name: "patroni-node2"
        #    static_configs:
        #      - targets: ["10.129.0.10:9933"]
  - job_name: 'etcd'
    static_configs:
    - targets: ['10.129.0.24:2379','10.129.0.10:2379','10.129.0.7:2379']
  - job_name: 'PTR2'
    static_configs:
    - targets: ['10.129.0.24:8008','10.129.0.10:8008']
  - job_name: 'Haproxy1'
    static_configs:
    - targets: ['10.129.0.7:8404']
  - job_name: 'Haproxy2'
    static_configs:
    - targets: ['10.129.0.7:9101']
  - job_name: "PostgresDB2"
    static_configs:
      - targets: ['10.129.0.24:5432','10.129.0.10:5432']
 
