{
 "title": "ETCD",
 "description": "Etcd Dashboard from Prometheus for clusters running etcd as processes (not containers)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Info",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"})*100"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\",job=~\"$cluster\"}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "sum(etcd_server_is_leader{instance=~\"$instance\",job=~\"$cluster\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{instance=~\"$instance\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "The number of leader changes seen total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{instance=~\"$instance\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Etcd Members",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_id{instance=~\"$instance\",job=~\"$cluster\"})",
     "legendFormat": "members"
    }
   ]
  },
  {
   "title": "DB Info per Member",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "% DB Space Used $instance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"})*100"
    }
   ]
  },
  {
   "title": "DB Size Limit (Backend-bytes) $instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"} ",
     "legendFormat": "{{ instance }} Quota Bytes"
    }
   ]
  },
  {
   "title": "General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} Resident Memory"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{instance=~\"$instance\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "total number of consensus proposals committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{instance=~\"$instance\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_sum{instance=~\"$instance\",job=~\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }} The latency distributions of fsync called by wal"
    },
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_sum{instance=~\"$instance\",job=~\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }} The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{ instance }} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{ instance }} DB fsync"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} DB Size"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} Used bytes"
    }
   ]
  },
  {
   "title": "Members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_id{instance=~\"$instance\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Slow operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_slow_apply_total{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} slow applies"
    },
    {
     "expr": "etcd_server_slow_read_indexes_total{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} slow read indexes"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_keys_total{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance }} Num keys"
    }
   ]
  },
  {
   "title": "Key Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_put_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} puts/s"
    },
    {
     "expr": "rate(etcd_debugging_mvcc_delete_total{instance=~\"$instance\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} deletes/s"
    }
   ]
  },
  {
   "title": "Defrag time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_backend_defrag_duration_seconds_sum{instance=~\"$instance\",job=~\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }} latency distributions of defrag"
    }
   ]
  },
  {
   "title": "Compacted Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$cluster\"}",
     "legendFormat": "{{ instance  }} keys compacted "
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[1m]))",
     "legendFormat": "The total number of bytes received by grpc clients"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$instance\",job=~\"$cluster\"}[1m]))",
     "legendFormat": "The total number of bytes sent to grpc clients"
    }
   ]
  }
 ]
}