{
 "title": "HAproxy",
 "description": "HAproxy ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(haproxy_process_uptime_seconds,instance)"
    }
   },
   {
    "name": "proxy",
    "label": "Proxy",
    "query": {
     "query": "label_values({instance=~\"$instance\"},proxy)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(haproxy_server_current_sessions{instance=~\"$instance\", proxy=~\"$proxy\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_frontend_status{instance=~\"$instance\", proxy=~\"$proxy\"}>0"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "%Active Sessions for  $proxy",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "repeat": "proxy",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{instance=~\"$instance\", proxy=~\"$proxy\"}/haproxy_frontend_limit_sessions{instance=~\"$instance\", proxy=~\"$proxy\"}*100",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "New Session Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(haproxy_frontend_current_sessions{instance=~\"$instance\", proxy=~\"$proxy\"}[180s])",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{instance=~\"$instance\", proxy=~\"$proxy\"}",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Sessions for servers $server",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "repeat": "server",
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{instance=~\"$instance\", proxy=~\"$proxy\",server=~\"$server\"}",
     "legendFormat": "{{instance}} / {{proxy}} / {{server}}"
    }
   ]
  },
  {
   "title": "Max Session Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "haproxy_frontend_max_session_rate{instance=~\"$instance\", proxy=~\"$proxy\"}",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "New Connections Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(haproxy_frontend_connections_total{instance=~\"$instance\", proxy=~\"$proxy\"}[180s])",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  { "title": "Time for different servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Total time (average) on $server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "repeat": "server",
   "targets": [
    {
     "expr": "haproxy_server_total_time_average_seconds{instance=~\"$instance\", proxy=~\"$proxy\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Max total time on $server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "repeat": "server",
   "targets": [
    {
     "expr": "haproxy_server_max_total_time_seconds{instance=~\"$instance\", proxy=~\"$proxy\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bytes IN",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": " irate(haproxy_frontend_bytes_in_total{instance=~\"$instance\", proxy=~\"$proxy\"}[180s])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Rate bytes OUT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(haproxy_frontend_bytes_out_total{instance=~\"$instance\", proxy=~\"$proxy\"}[180s])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(haproxy_frontend_request_errors_total{instance=~\"$instance\", proxy=~\"$proxy\"}[180s])",
       "legendFormat": " {{proxy}}"
      }
     ]
    },
    {
     "title": "Requests Denied",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(haproxy_frontend_requests_denied_total{instance=~\"$instance\", proxy=~\"$proxy\"}[180s])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  }
 ]
}