{
 "title": "Patroni_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Common info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Patroni version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_cluster_node_static{job=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Choose" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~\"$cluster\", instance=~\"$instance\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(\n  patroni_cluster_node_state{instance=~\"$instance\", job=~\"$cluster\"}>0\n)\n  * on(instance,job,scope) group_left(role) \n(\n  (patroni_cluster_node_role{instance=~\"$instance\", job=~\"$cluster\"})>0\n)\n  * on(instance,job) group_left(Value)  process_start_time_seconds{job=~\"$cluster\", instance=~\"$instance\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Other metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(process_resident_memory_bytes{job=~\"$cluster\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{lable}}"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$cluster\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Resident memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=~\"$cluster\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maximum number of open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "process_max_fds{job=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } }
 ]
}