{
 "title": "PostgreSQL Database mult",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{job=\"$namespace\"},instance)"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "mode",
    "label": "Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"},mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and Replication lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{instance=~\"$instance\", job=~\"$namespace\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{job=\"$namespace\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"$namespace\", instance=\"$instance\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{job=\"$namespace\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Shared Buffers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_seq_page_cost{job=\"$namespace\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Replication lag (mb)",
   "type": "timeseries",
   "description": "Lag in bytes between master and slave",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff{job=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Replication lag (seconds)",
   "type": "timeseries",
   "description": "Replication lag behind primary in seconds, as detected after a roundtrip on the primary.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_replication_lag_seconds{job=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoints stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total{instance=\"$instance\", job=~\"$namespace\"}[1m])",
       "legendFormat": "Written Files to disk"
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time_total{instance=\"$instance\", job=~\"$namespace\"}[1m])",
       "legendFormat": "Files Synchronization to disk"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers & Blocks Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffers (bgwriter)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{instance=\"$instance\", job=~\"$namespace\"}[1m])",
       "legendFormat": "Allocated"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{instance=\"$instance\",job=~\"$namespace\"}[1m])",
       "legendFormat": "Fsync calls by a backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_total{instance=\"$instance\",job=~\"$namespace\"}[1m])",
       "legendFormat": "Written directly by a backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean_total{instance=\"$instance\",job=~\"$namespace\"}[1m])",
       "legendFormat": "Written by the background writer"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{instance=\"$instance\",job=~\"$namespace\"}[1m])",
       "legendFormat": "Written during checkpoints"
      }
     ]
    },
    {
     "title": "Operations with Blocks",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "rd/s" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_blk_read_time{datname=~\"$datname\", instance=~\"$instance\", job=~\"$namespace\"}[5m])",
       "legendFormat": "Read {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_blk_write_time{datname=~\"$datname\",instance=~\"$instance\", job=~\"$namespace\"}[5m])",
       "legendFormat": "Write {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(datname) (pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{job=~\"$namespace\",instance=~\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{job=~\"$namespace\",instance=~\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{job=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\", job=~\"$namespace\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\", job=~\"$namespace\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\", job=~\"$namespace\"} [30s])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$instance\", mode=~\"$mode\", job=~\"$namespace\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\", job=~\"$namespace\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\", job=~\"$namespace\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Idle sessions database : $datname",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "repeat": "datname",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(datname,state) (pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\", job=~\"$namespace\"})",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\", job=~\"$namespace\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=~\"$datname\", job=~\"$namespace\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\", job=~\"$namespace\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\", job=~\"$namespace\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\", datname=~\"$datname\", job=~\"$namespace\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}